test:
  workers:
    number: 100
  rounds:
    - label: Init MLTask 2000.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 2000
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000
    - label: Init MLTask 1900.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1900
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1800.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1800
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1700.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1700
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1600.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1600
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1500.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1500
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1400.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1400
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1300.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1300
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1200.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1200
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1100.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1100
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 1000.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 900.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 900
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 800.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 800
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 700.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 600.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 600
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 500.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 400.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 300.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 200.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    - label: Init MLTask 100.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/initMLTask.js
        arguments:
          limit: 1000

    # - label: Submit model 2000.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 2000
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000
    # - label: Submit model 1900.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1900
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1800.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1800
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1700.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1700
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1600.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1600
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1500.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1500
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1400.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1400
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1300.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1300
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1200.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1200
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1100.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1100
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 1000.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 1000
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 900.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 900
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 800.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 800
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 700.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 700
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 600.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 600
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 500.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 500
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 400.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 400
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 300.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 300
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 200.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 200
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # - label: Submit model 100.
    #   txDuration: 30
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 100
    #   workload:
    #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/submitModel.js
    #     arguments:
    #       limit: 1000

    # # - label: Query 2000.
    # #   txDuration: 30
    # #   rateControl:
    # #     type: fixed-rate
    # #     opts:
    # #       tps: 2000
    # #   workload:
    # #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/queryMLTask.js
    # #     arguments:
    # #       limit: 1000

    # # - label: Query 100.
    # #   txDuration: 30
    # #   rateControl:
    # #     type: fixed-rate
    # #     opts:
    # #       tps: 100
    # #   workload:
    # #     module: benchmarks/samples/fabric/MetaCrowd/ModelExchange/queryMLTask.js
    # #     arguments:
    # #       limit: 1000

